# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 026344b0e04ae1c7aa09c75ff6fb97dc3628387063d944588945b291885a4c8f8aa8f9cc602210276036cee77badae8e0f2d669e14a48f78888b6d41fecc9faf

test:
  secret_key_base: 412c21205592f0903dd58230388d2ce11bf4b4bbc2d08ade78c61da647eb37dffaf46bac7f54ccfb9fd936485cfd0a3f1c8d24933bc5033cb78b3746a34666aa

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
